# Generated by Django 4.0 on 2024-10-16 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('item', '0002_alter_item_id'),
        ('eatery', '0005_alter_eatery_campus_area'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('netid', models.CharField(blank=True, max_length=10, null=True)),
                ('name', models.CharField(default='User', max_length=40)),
                ('is_admin', models.BooleanField(default=False)),
                ('favorite_eateries', models.ManyToManyField(blank=True, related_name='favorited_by', to='eatery.Eatery')),
                ('favorite_items', models.ManyToManyField(blank=True, related_name='favorited_by', to='item.Item')),
            ],
        ),
    ]
