# Generated by Django 4.0 on 2024-10-30 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userfcmdevice',
            name='fcm_device',
        ),
        migrations.AddField(
            model_name='userfcmdevice',
            name='device_id',
            field=models.CharField(default='default_device_id', max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='userfcmdevice',
            name='registration_id',
            field=models.CharField(default='default_registration_id', max_length=255),
        ),
        migrations.AddField(
            model_name='userfcmdevice',
            name='type',
            field=models.CharField(default='unknown', max_length=10),
        ),
        migrations.AlterField(
            model_name='userfcmdevice',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fcm_devices', to='user.user'),
        ),
    ]
