# Generated by Django 4.0 on 2024-10-09 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eatery', '0005_alter_eatery_campus_area'),
        ('item', '0002_alter_item_id'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favorite_eateries',
            field=models.ManyToManyField(blank=True, related_name='favorited_by', to='eatery.Eatery'),
        ),
        migrations.AddField(
            model_name='user',
            name='favorite_items',
            field=models.ManyToManyField(blank=True, related_name='favorited_by', to='item.Item'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default='User', max_length=40),
        ),
    ]
