# Generated by Django 4.0 on 2025-03-04 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_brb_balance_user_city_bucks_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='laundry_balance',
            field=models.FloatField(default=0),
        ),
    ]
