# Generated by Django 4.0 on 2025-03-04 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_user_laundry_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='brb_account_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='citybucks_account_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='laundry_account_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
