# Generated by Django 4.0 on 2025-03-04 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_user_brb_account_name_user_citybucks_account_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='citybucks_account_name',
            new_name='city_bucks_account_name',
        ),
    ]
