# Generated by Django 4.0 on 2025-10-01 16:30

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_rename_citybucks_account_name_user_city_bucks_account_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='brb_account_name',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='user',
            name='city_bucks_account_name',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='user',
            name='device_id',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='user',
            name='favorite_items',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=256), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='user',
            name='fcm_token',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='user',
            name='laundry_account_name',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
