version: "3.8"

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: eatery_app
      POSTGRES_PASSWORD: password
      POSTGRES_DB: eatery_blue
    ports:
      - "5432:5432"
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data

volumes:
  postgres_dev_data:
