# Generated by Django 4.0 on 2024-12-04 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceToken',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('device_token', models.CharField(max_length=255, unique=True)),
            ],
        ),
    ]
