# Generated by Django 4.0 on 2024-02-29 04:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("report", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="netid",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
