# Generated by Django 4.0 on 2025-10-26 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_alter_event_event_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='downvotes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='event',
            name='upvotes',
            field=models.IntegerField(default=0),
        ),
    ]
