# Generated by Django 4.0 on 2024-02-29 21:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("eatery", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eatery",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
